<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412130439 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agencies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(180) NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, rating DOUBLE PRECISION NOT NULL, total_reviews INT NOT NULL, is_verified BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F65A4DC4989D9B62 ON agencies (slug)');
        $this->addSql('CREATE INDEX IDX_F65A4DC47E3C61F9 ON agencies (owner_id)');
        $this->addSql('CREATE TABLE analytics_dashboards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, layout JSON NOT NULL, widgets JSON NOT NULL, filters JSON DEFAULT NULL, is_default BOOLEAN NOT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, agency_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8806A29A76ED395 ON analytics_dashboards (user_id)');
        $this->addSql('CREATE INDEX IDX_B8806A29CDEADB2A ON analytics_dashboards (agency_id)');
        $this->addSql('CREATE TABLE analytics_metrics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, value NUMERIC(15, 2) DEFAULT NULL, data JSON DEFAULT NULL, unit VARCHAR(20) DEFAULT NULL, period VARCHAR(50) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, previous_value NUMERIC(15, 2) DEFAULT NULL, change_percentage NUMERIC(5, 2) DEFAULT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dashboard_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_88282619B9D04D2B ON analytics_metrics (dashboard_id)');
        $this->addSql('CREATE TABLE bookings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(20) NOT NULL, status VARCHAR(50) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, number_of_seats INT NOT NULL, seat_numbers JSON NOT NULL, passengers JSON NOT NULL, special_requests TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7A853C35AEA34913 ON bookings (reference)');
        $this->addSql('CREATE INDEX IDX_7A853C35A76ED395 ON bookings (user_id)');
        $this->addSql('CREATE INDEX IDX_7A853C35A5BC2E0E ON bookings (trip_id)');
        $this->addSql('CREATE TABLE chat_conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5813432EA76ED395 ON chat_conversations (user_id)');
        $this->addSql('CREATE TABLE chat_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF20C9A69AC0396 ON chat_messages (conversation_id)');
        $this->addSql('CREATE TABLE delay_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, delay_minutes INT NOT NULL, reason VARCHAR(100) DEFAULT NULL, conditions JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FF4BD32A5BC2E0E ON delay_history (trip_id)');
        $this->addSql('CREATE TABLE delay_predictions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, predicted_delay_minutes INT NOT NULL, confidence_score NUMERIC(5, 2) NOT NULL, risk_level VARCHAR(50) NOT NULL, factors JSON DEFAULT NULL, reasoning TEXT DEFAULT NULL, predicted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actual_arrival_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actual_delay_minutes INT DEFAULT NULL, is_accurate BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A8DEDAEA5BC2E0E ON delay_predictions (trip_id)');
        $this->addSql('CREATE TABLE multi_modal_trip_segments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, segment_order INT NOT NULL, departure_city VARCHAR(100) NOT NULL, arrival_city VARCHAR(100) NOT NULL, departure_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, duration INT DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, transfer_duration INT DEFAULT NULL, transfer_notes VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, multi_modal_trip_id INT NOT NULL, trip_id INT DEFAULT NULL, transport_mode_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_323623D2C0F47AE2 ON multi_modal_trip_segments (multi_modal_trip_id)');
        $this->addSql('CREATE INDEX IDX_323623D2A5BC2E0E ON multi_modal_trip_segments (trip_id)');
        $this->addSql('CREATE INDEX IDX_323623D2E33245BB ON multi_modal_trip_segments (transport_mode_id)');
        $this->addSql('CREATE TABLE multi_modal_trips (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_city VARCHAR(100) NOT NULL, arrival_city VARCHAR(100) NOT NULL, departure_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_price NUMERIC(10, 2) DEFAULT NULL, total_duration INT DEFAULT NULL, total_distance DOUBLE PRECISION DEFAULT NULL, status VARCHAR(50) NOT NULL, preferences JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45F74107A76ED395 ON multi_modal_trips (user_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, data JSON DEFAULT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, method VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(50) NOT NULL, transaction_id VARCHAR(255) NOT NULL, provider_reference VARCHAR(255) DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, booking_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_65D29B322FC0CB0F ON payments (transaction_id)');
        $this->addSql('CREATE INDEX IDX_65D29B323301C60 ON payments (booking_id)');
        $this->addSql('CREATE INDEX IDX_65D29B32A76ED395 ON payments (user_id)');
        $this->addSql('CREATE TABLE pricing_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_price NUMERIC(10, 2) NOT NULL, final_price NUMERIC(10, 2) NOT NULL, multiplier NUMERIC(5, 2) NOT NULL, factors JSON DEFAULT NULL, status VARCHAR(50) NOT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, pricing_rule_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E641FEA1A5BC2E0E ON pricing_history (trip_id)');
        $this->addSql('CREATE INDEX IDX_E641FEA1B5B58DBB ON pricing_history (pricing_rule_id)');
        $this->addSql('CREATE TABLE pricing_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, conditions JSON NOT NULL, multiplier NUMERIC(5, 2) NOT NULL, min_price NUMERIC(10, 2) DEFAULT NULL, max_price NUMERIC(10, 2) DEFAULT NULL, priority INT NOT NULL, is_active BOOLEAN NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A56811BDCDEADB2A ON pricing_rules (agency_id)');
        $this->addSql('CREATE TABLE recommendation_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, recommendation_data JSON NOT NULL, relevance_score NUMERIC(5, 2) NOT NULL, was_clicked BOOLEAN NOT NULL, was_booked BOOLEAN NOT NULL, clicked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, booked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, trip_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AD979E7A76ED395 ON recommendation_history (user_id)');
        $this->addSql('CREATE INDEX IDX_7AD979E7A5BC2E0E ON recommendation_history (trip_id)');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, agency_id INT NOT NULL, booking_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0FA76ED395 ON reviews (user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FCDEADB2A ON reviews (agency_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F3301C60 ON reviews (booking_id)');
        $this->addSql('CREATE TABLE tickets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qr_code VARCHAR(255) NOT NULL, qr_code_data JSON NOT NULL, status VARCHAR(50) NOT NULL, seat_number INT NOT NULL, passenger_name VARCHAR(255) NOT NULL, passenger_phone VARCHAR(20) NOT NULL, scanned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54469DF47D8B1FB5 ON tickets (qr_code)');
        $this->addSql('CREATE INDEX IDX_54469DF43301C60 ON tickets (booking_id)');
        $this->addSql('CREATE INDEX IDX_54469DF4A76ED395 ON tickets (user_id)');
        $this->addSql('CREATE TABLE transport_modes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, description VARCHAR(255) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE trips (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_city VARCHAR(100) NOT NULL, arrival_city VARCHAR(100) NOT NULL, departure_address VARCHAR(255) NOT NULL, arrival_address VARCHAR(255) NOT NULL, departure_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, available_seats INT NOT NULL, total_seats INT NOT NULL, status VARCHAR(50) NOT NULL, distance DOUBLE PRECISION DEFAULT NULL, duration INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, vehicle_id INT NOT NULL, transport_mode_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA7370DACDEADB2A ON trips (agency_id)');
        $this->addSql('CREATE INDEX IDX_AA7370DA545317D1 ON trips (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_AA7370DAE33245BB ON trips (transport_mode_id)');
        $this->addSql('CREATE TABLE user_preferences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, preferred_routes JSON DEFAULT NULL, preferred_agencies JSON DEFAULT NULL, preferred_vehicle_types JSON DEFAULT NULL, preferred_time_slots JSON DEFAULT NULL, preferred_amenities JSON DEFAULT NULL, budget_range VARCHAR(20) DEFAULT NULL, prefers_eco_friendly BOOLEAN DEFAULT NULL, prefers_express BOOLEAN DEFAULT NULL, notification_preferences JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_402A6F60A76ED395 ON user_preferences (user_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, preferred_language VARCHAR(10) NOT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE vehicles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, brand VARCHAR(100) NOT NULL, model VARCHAR(100) NOT NULL, plate_number VARCHAR(20) NOT NULL, total_seats INT NOT NULL, amenities JSON NOT NULL, is_electric BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, last_maintenance_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agency_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1FCE69FAFCFF3785 ON vehicles (plate_number)');
        $this->addSql('CREATE INDEX IDX_1FCE69FACDEADB2A ON vehicles (agency_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE agencies ADD CONSTRAINT FK_F65A4DC47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_dashboards ADD CONSTRAINT FK_B8806A29A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_dashboards ADD CONSTRAINT FK_B8806A29CDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_metrics ADD CONSTRAINT FK_88282619B9D04D2B FOREIGN KEY (dashboard_id) REFERENCES analytics_dashboards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C35A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bookings ADD CONSTRAINT FK_7A853C35A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_conversations ADD CONSTRAINT FK_5813432EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A69AC0396 FOREIGN KEY (conversation_id) REFERENCES chat_conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delay_history ADD CONSTRAINT FK_7FF4BD32A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delay_predictions ADD CONSTRAINT FK_A8DEDAEA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE multi_modal_trip_segments ADD CONSTRAINT FK_323623D2C0F47AE2 FOREIGN KEY (multi_modal_trip_id) REFERENCES multi_modal_trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE multi_modal_trip_segments ADD CONSTRAINT FK_323623D2A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE multi_modal_trip_segments ADD CONSTRAINT FK_323623D2E33245BB FOREIGN KEY (transport_mode_id) REFERENCES transport_modes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE multi_modal_trips ADD CONSTRAINT FK_45F74107A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B323301C60 FOREIGN KEY (booking_id) REFERENCES bookings (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pricing_history ADD CONSTRAINT FK_E641FEA1A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pricing_history ADD CONSTRAINT FK_E641FEA1B5B58DBB FOREIGN KEY (pricing_rule_id) REFERENCES pricing_rules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pricing_rules ADD CONSTRAINT FK_A56811BDCDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation_history ADD CONSTRAINT FK_7AD979E7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation_history ADD CONSTRAINT FK_7AD979E7A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trips (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FCDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F3301C60 FOREIGN KEY (booking_id) REFERENCES bookings (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF43301C60 FOREIGN KEY (booking_id) REFERENCES bookings (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tickets ADD CONSTRAINT FK_54469DF4A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT FK_AA7370DACDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT FK_AA7370DA545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trips ADD CONSTRAINT FK_AA7370DAE33245BB FOREIGN KEY (transport_mode_id) REFERENCES transport_modes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_preferences ADD CONSTRAINT FK_402A6F60A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicles ADD CONSTRAINT FK_1FCE69FACDEADB2A FOREIGN KEY (agency_id) REFERENCES agencies (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agencies DROP CONSTRAINT FK_F65A4DC47E3C61F9');
        $this->addSql('ALTER TABLE analytics_dashboards DROP CONSTRAINT FK_B8806A29A76ED395');
        $this->addSql('ALTER TABLE analytics_dashboards DROP CONSTRAINT FK_B8806A29CDEADB2A');
        $this->addSql('ALTER TABLE analytics_metrics DROP CONSTRAINT FK_88282619B9D04D2B');
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C35A76ED395');
        $this->addSql('ALTER TABLE bookings DROP CONSTRAINT FK_7A853C35A5BC2E0E');
        $this->addSql('ALTER TABLE chat_conversations DROP CONSTRAINT FK_5813432EA76ED395');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A69AC0396');
        $this->addSql('ALTER TABLE delay_history DROP CONSTRAINT FK_7FF4BD32A5BC2E0E');
        $this->addSql('ALTER TABLE delay_predictions DROP CONSTRAINT FK_A8DEDAEA5BC2E0E');
        $this->addSql('ALTER TABLE multi_modal_trip_segments DROP CONSTRAINT FK_323623D2C0F47AE2');
        $this->addSql('ALTER TABLE multi_modal_trip_segments DROP CONSTRAINT FK_323623D2A5BC2E0E');
        $this->addSql('ALTER TABLE multi_modal_trip_segments DROP CONSTRAINT FK_323623D2E33245BB');
        $this->addSql('ALTER TABLE multi_modal_trips DROP CONSTRAINT FK_45F74107A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B323301C60');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32A76ED395');
        $this->addSql('ALTER TABLE pricing_history DROP CONSTRAINT FK_E641FEA1A5BC2E0E');
        $this->addSql('ALTER TABLE pricing_history DROP CONSTRAINT FK_E641FEA1B5B58DBB');
        $this->addSql('ALTER TABLE pricing_rules DROP CONSTRAINT FK_A56811BDCDEADB2A');
        $this->addSql('ALTER TABLE recommendation_history DROP CONSTRAINT FK_7AD979E7A76ED395');
        $this->addSql('ALTER TABLE recommendation_history DROP CONSTRAINT FK_7AD979E7A5BC2E0E');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FA76ED395');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FCDEADB2A');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F3301C60');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF43301C60');
        $this->addSql('ALTER TABLE tickets DROP CONSTRAINT FK_54469DF4A76ED395');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT FK_AA7370DACDEADB2A');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT FK_AA7370DA545317D1');
        $this->addSql('ALTER TABLE trips DROP CONSTRAINT FK_AA7370DAE33245BB');
        $this->addSql('ALTER TABLE user_preferences DROP CONSTRAINT FK_402A6F60A76ED395');
        $this->addSql('ALTER TABLE vehicles DROP CONSTRAINT FK_1FCE69FACDEADB2A');
        $this->addSql('DROP TABLE agencies');
        $this->addSql('DROP TABLE analytics_dashboards');
        $this->addSql('DROP TABLE analytics_metrics');
        $this->addSql('DROP TABLE bookings');
        $this->addSql('DROP TABLE chat_conversations');
        $this->addSql('DROP TABLE chat_messages');
        $this->addSql('DROP TABLE delay_history');
        $this->addSql('DROP TABLE delay_predictions');
        $this->addSql('DROP TABLE multi_modal_trip_segments');
        $this->addSql('DROP TABLE multi_modal_trips');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE pricing_history');
        $this->addSql('DROP TABLE pricing_rules');
        $this->addSql('DROP TABLE recommendation_history');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE tickets');
        $this->addSql('DROP TABLE transport_modes');
        $this->addSql('DROP TABLE trips');
        $this->addSql('DROP TABLE user_preferences');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE vehicles');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
